// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"time"
)

type ApiCache struct {
	ID        int64     `json:"id"`
	Year      int64     `json:"year"`
	CreatedAt time.Time `json:"created_at"`
}

type Event struct {
	ID          int64     `json:"id"`
	ScheduledAt time.Time `json:"scheduled_at"`
	Name        string    `json:"name"`
	State       string    `json:"state"`
	CreatedAt   time.Time `json:"created_at"`
	EditedAt    time.Time `json:"edited_at"`
	UserID      int64     `json:"user_id"`
}

type Notification struct {
	ID        int64      `json:"id"`
	Message   string     `json:"message"`
	CreatedAt time.Time  `json:"created_at"`
	ViewedAt  *time.Time `json:"viewed_at"`
}

type NotificationUser struct {
	NotificationID int64 `json:"notification_id"`
	UserID         int64 `json:"user_id"`
}

type Request struct {
	ID        int64     `json:"id"`
	Message   *string   `json:"message"`
	State     string    `json:"state"`
	CreatedAt time.Time `json:"created_at"`
	EditedAt  time.Time `json:"edited_at"`
	UserID    int64     `json:"user_id"`
	EditedBy  *int64    `json:"edited_by"`
	EventID   int64     `json:"event_id"`
}

type Session struct {
	ID         string    `json:"id"`
	ValidUntil time.Time `json:"valid_until"`
	CreatedAt  time.Time `json:"created_at"`
	EditedAt   time.Time `json:"edited_at"`
	UserID     int64     `json:"user_id"`
}

type Setting struct {
	ID            int64 `json:"id"`
	SignupEnabled bool  `json:"signup_enabled"`
}

type Timestamp struct {
	ID        int64      `json:"id"`
	StartTime time.Time  `json:"start_time"`
	EndTime   *time.Time `json:"end_time"`
	UserID    int64      `json:"user_id"`
}

type TokenRefresh struct {
	ID        int64     `json:"id"`
	Year      int64     `json:"year"`
	UserID    int64     `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID           int64     `json:"id"`
	Username     string    `json:"username"`
	Email        string    `json:"email"`
	Password     string    `json:"password"`
	VacationDays int64     `json:"vacation_days"`
	IsSuperuser  bool      `json:"is_superuser"`
	CreatedAt    time.Time `json:"created_at"`
	EditedAt     time.Time `json:"edited_at"`
	Color        string    `json:"color"`
	Role         string    `json:"role"`
	Enabled      bool      `json:"enabled"`
	AworkID      *string   `json:"awork_id"`
}

type VacationToken struct {
	ID        int64     `json:"id"`
	StartDate time.Time `json:"start_date"`
	EndDate   time.Time `json:"end_date"`
	Value     float64   `json:"value"`
	UserID    int64     `json:"user_id"`
}
