// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"
	"time"
)

type Querier interface {
	CacheExists(ctx context.Context, year int64) (int64, error)
	ClearAllUserNotifications(ctx context.Context, userID int64) error
	ClearNotification(ctx context.Context, id int64) (Notification, error)
	CreateCache(ctx context.Context, year int64) error
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	CreateNotification(ctx context.Context, message string) (Notification, error)
	CreateNotificationUser(ctx context.Context, arg CreateNotificationUserParams) error
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (TokenRefresh, error)
	CreateRequest(ctx context.Context, arg CreateRequestParams) (Request, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateSettings(ctx context.Context, signupEnabled bool) (Setting, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVacationToken(ctx context.Context, arg CreateVacationTokenParams) (VacationToken, error)
	DeleteAllRefreshTokens(ctx context.Context) error
	DeleteAllSessions(ctx context.Context) error
	DeleteAllVacationTokens(ctx context.Context) error
	DeleteEvent(ctx context.Context, id int64) error
	DeleteSession(ctx context.Context, id string) error
	DeleteSettings(ctx context.Context, id int64) error
	DeleteTimestamp(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id int64) error
	DeleteVacationToken(ctx context.Context, id int64) error
	GetAdmins(ctx context.Context) ([]User, error)
	GetAllTimestampsForUser(ctx context.Context, userID int64) ([]Timestamp, error)
	GetAllTimestampsInRange(ctx context.Context, arg GetAllTimestampsInRangeParams) ([]Timestamp, error)
	GetAllUsers(ctx context.Context) ([]User, error)
	GetApiCacheYears(ctx context.Context) ([]int64, error)
	GetConflictingEventUsers(ctx context.Context, arg GetConflictingEventUsersParams) ([]User, error)
	GetEventById(ctx context.Context, id int64) (Event, error)
	GetEventNameFromRequest(ctx context.Context, id int64) (string, error)
	GetEventsByUserId(ctx context.Context, userID int64) ([]Event, error)
	GetEventsForDay(ctx context.Context, scheduledAt time.Time) ([]Event, error)
	GetEventsForMonth(ctx context.Context, arg GetEventsForMonthParams) ([]GetEventsForMonthRow, error)
	GetEventsForYear(ctx context.Context, arg GetEventsForYearParams) ([]GetEventsForYearRow, error)
	GetLatestTimestamp(ctx context.Context, userID int64) (Timestamp, error)
	GetPendingEventsForYear(ctx context.Context, arg GetPendingEventsForYearParams) (int64, error)
	GetPendingRequests(ctx context.Context) ([]GetPendingRequestsRow, error)
	GetRefreshToken(ctx context.Context, arg GetRefreshTokenParams) (int64, error)
	GetRemainingVacationForUser(ctx context.Context, arg GetRemainingVacationForUserParams) (*float64, error)
	GetRequestRange(ctx context.Context, arg GetRequestRangeParams) ([]Request, error)
	GetSessionById(ctx context.Context, id string) (Session, error)
	GetSettingsById(ctx context.Context, id int64) (Setting, error)
	GetTimestampById(ctx context.Context, id int64) (Timestamp, error)
	GetTimestampsInRange(ctx context.Context, arg GetTimestampsInRangeParams) ([]Timestamp, error)
	GetTotalSecondsInRange(ctx context.Context, arg GetTotalSecondsInRangeParams) (*float64, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetUserByName(ctx context.Context, username string) (User, error)
	GetUserFromSession(ctx context.Context, id string) (User, error)
	GetUserNotifications(ctx context.Context, userID int64) ([]Notification, error)
	GetVacationCountForUser(ctx context.Context, arg GetVacationCountForUserParams) (*float64, error)
	StartTimestamp(ctx context.Context, userID int64) (Timestamp, error)
	StopTimestamp(ctx context.Context, id int64) (Timestamp, error)
	UpdateEventState(ctx context.Context, arg UpdateEventStateParams) (Event, error)
	UpdateEventsRange(ctx context.Context, arg UpdateEventsRangeParams) error
	UpdateNotification(ctx context.Context, message string) (Notification, error)
	UpdateRequest(ctx context.Context, arg UpdateRequestParams) (Request, error)
	UpdateRequestStateRange(ctx context.Context, arg UpdateRequestStateRangeParams) (int64, error)
	UpdateSettings(ctx context.Context, arg UpdateSettingsParams) (Setting, error)
	UpdateTimestamp(ctx context.Context, arg UpdateTimestampParams) (Timestamp, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
