// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: timestamps.sql

package repo

import (
	"context"
	"time"
)

const DeleteTimestamp = `-- name: DeleteTimestamp :exec
DELETE FROM timestamps
WHERE id = ?
`

func (q *Queries) DeleteTimestamp(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, DeleteTimestamp, id)
	return err
}

const GetAllTimestampsForUser = `-- name: GetAllTimestampsForUser :many
SELECT id, start_time, end_time, user_id FROM timestamps
WHERE user_id = ?
`

func (q *Queries) GetAllTimestampsForUser(ctx context.Context, userID int64) ([]Timestamp, error) {
	rows, err := q.db.QueryContext(ctx, GetAllTimestampsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Timestamp
	for rows.Next() {
		var i Timestamp
		if err := rows.Scan(
			&i.ID,
			&i.StartTime,
			&i.EndTime,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetAllTimestampsInRange = `-- name: GetAllTimestampsInRange :many
SELECT id, start_time, end_time, user_id FROM timestamps
WHERE start_time < ?1
AND end_time IS NOT NULL
AND end_time > ?2
`

type GetAllTimestampsInRangeParams struct {
	EndTime   time.Time  `json:"end_time"`
	StartTime *time.Time `json:"start_time"`
}

func (q *Queries) GetAllTimestampsInRange(ctx context.Context, arg GetAllTimestampsInRangeParams) ([]Timestamp, error) {
	rows, err := q.db.QueryContext(ctx, GetAllTimestampsInRange, arg.EndTime, arg.StartTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Timestamp
	for rows.Next() {
		var i Timestamp
		if err := rows.Scan(
			&i.ID,
			&i.StartTime,
			&i.EndTime,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetLatestTimestamp = `-- name: GetLatestTimestamp :one
SELECT id, start_time, end_time, user_id FROM timestamps
WHERE user_id = ?
ORDER BY id DESC
`

func (q *Queries) GetLatestTimestamp(ctx context.Context, userID int64) (Timestamp, error) {
	row := q.db.QueryRowContext(ctx, GetLatestTimestamp, userID)
	var i Timestamp
	err := row.Scan(
		&i.ID,
		&i.StartTime,
		&i.EndTime,
		&i.UserID,
	)
	return i, err
}

const GetTimestampById = `-- name: GetTimestampById :one
SELECT id, start_time, end_time, user_id FROM timestamps
WHERE id = ?
`

func (q *Queries) GetTimestampById(ctx context.Context, id int64) (Timestamp, error) {
	row := q.db.QueryRowContext(ctx, GetTimestampById, id)
	var i Timestamp
	err := row.Scan(
		&i.ID,
		&i.StartTime,
		&i.EndTime,
		&i.UserID,
	)
	return i, err
}

const GetTimestampsInRange = `-- name: GetTimestampsInRange :many
SELECT id, start_time, end_time, user_id FROM timestamps
WHERE user_id = ?
AND start_time < ?
AND end_time IS NOT NULL
AND end_time > ?
`

type GetTimestampsInRangeParams struct {
	UserID    int64      `json:"user_id"`
	EndTime   time.Time  `json:"end_time"`
	StartTime *time.Time `json:"start_time"`
}

func (q *Queries) GetTimestampsInRange(ctx context.Context, arg GetTimestampsInRangeParams) ([]Timestamp, error) {
	rows, err := q.db.QueryContext(ctx, GetTimestampsInRange, arg.UserID, arg.EndTime, arg.StartTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Timestamp
	for rows.Next() {
		var i Timestamp
		if err := rows.Scan(
			&i.ID,
			&i.StartTime,
			&i.EndTime,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetTotalSecondsInRange = `-- name: GetTotalSecondsInRange :one
SELECT
  SUM(
    MAX(
      0,
      strftime('%s', MIN(end_time, ?1))
      - strftime('%s', MAX(start_time, ?2))
    )
  ) AS total_seconds
FROM timestamps
WHERE user_id = ?3
  AND end_time IS NOT NULL
  AND start_time < ?1
  AND end_time > ?2
`

type GetTotalSecondsInRangeParams struct {
	RangeEnd   interface{} `json:"range_end"`
	RangeStart interface{} `json:"range_start"`
	UserID     int64       `json:"user_id"`
}

func (q *Queries) GetTotalSecondsInRange(ctx context.Context, arg GetTotalSecondsInRangeParams) (*float64, error) {
	row := q.db.QueryRowContext(ctx, GetTotalSecondsInRange, arg.RangeEnd, arg.RangeStart, arg.UserID)
	var total_seconds *float64
	err := row.Scan(&total_seconds)
	return total_seconds, err
}

const StartTimestamp = `-- name: StartTimestamp :one
INSERT INTO timestamps (user_id)
VALUES (?)
RETURNING id, start_time, end_time, user_id
`

func (q *Queries) StartTimestamp(ctx context.Context, userID int64) (Timestamp, error) {
	row := q.db.QueryRowContext(ctx, StartTimestamp, userID)
	var i Timestamp
	err := row.Scan(
		&i.ID,
		&i.StartTime,
		&i.EndTime,
		&i.UserID,
	)
	return i, err
}

const StopTimestamp = `-- name: StopTimestamp :one
UPDATE timestamps
SET end_time = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, start_time, end_time, user_id
`

func (q *Queries) StopTimestamp(ctx context.Context, id int64) (Timestamp, error) {
	row := q.db.QueryRowContext(ctx, StopTimestamp, id)
	var i Timestamp
	err := row.Scan(
		&i.ID,
		&i.StartTime,
		&i.EndTime,
		&i.UserID,
	)
	return i, err
}

const UpdateTimestamp = `-- name: UpdateTimestamp :one
UPDATE timestamps
SET start_time = ?,
end_time = ?
WHERE id = ?
RETURNING id, start_time, end_time, user_id
`

type UpdateTimestampParams struct {
	StartTime time.Time  `json:"start_time"`
	EndTime   *time.Time `json:"end_time"`
	ID        int64      `json:"id"`
}

func (q *Queries) UpdateTimestamp(ctx context.Context, arg UpdateTimestampParams) (Timestamp, error) {
	row := q.db.QueryRowContext(ctx, UpdateTimestamp, arg.StartTime, arg.EndTime, arg.ID)
	var i Timestamp
	err := row.Scan(
		&i.ID,
		&i.StartTime,
		&i.EndTime,
		&i.UserID,
	)
	return i, err
}
