// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: token_refresh.sql

package repo

import (
	"context"
)

const CreateTokenRefresh = `-- name: CreateTokenRefresh :one
INSERT INTO token_refresh (user_id, year)
VALUES (?,?)
RETURNING id, year, user_id, created_at
`

type CreateTokenRefreshParams struct {
	UserID int64 `json:"user_id"`
	Year   int64 `json:"year"`
}

func (q *Queries) CreateTokenRefresh(ctx context.Context, arg CreateTokenRefreshParams) (TokenRefresh, error) {
	row := q.db.QueryRowContext(ctx, CreateTokenRefresh, arg.UserID, arg.Year)
	var i TokenRefresh
	err := row.Scan(
		&i.ID,
		&i.Year,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const GetTokenRefresh = `-- name: GetTokenRefresh :one
SELECT Count(*) FROM token_refresh
WHERE user_id = ?
AND year = ?
`

type GetTokenRefreshParams struct {
	UserID int64 `json:"user_id"`
	Year   int64 `json:"year"`
}

func (q *Queries) GetTokenRefresh(ctx context.Context, arg GetTokenRefreshParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, GetTokenRefresh, arg.UserID, arg.Year)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const ResetTokenRefresh = `-- name: ResetTokenRefresh :exec
DELETE FROM token_refresh
`

func (q *Queries) ResetTokenRefresh(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, ResetTokenRefresh)
	return err
}
