-- +goose Up
CREATE TABLE IF NOT EXISTS events(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    scheduled_at DATETIME NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    edited_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    );

-- CREATE TABLE IF NOT EXISTS workers(
--     id INTEGER PRIMARY KEY AUTOINCREMENT,
--     name VARCHAR(50) NOT NULL UNIQUE,
--     state VARCHAR(10) NOT NULL,
--     metadata TEXT NOT NULL,
--     created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
--     edited_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
--
--     task_id INTEGER,
--     FOREIGN KEY(task_id) REFERENCES tasks(id)
--     );
--
-- CREATE TABLE IF NOT EXISTS jobs(
--     id INTEGER PRIMARY KEY AUTOINCREMENT,
--     name VARCHAR(50) NOT NULL,
--     priority INTEGER NOT NULL,
--     state VARCHAR(10) NOT NULL,
--     created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
--     edited_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
--     );

-- +goose Down
DROP TABLE IF EXISTS events;
