import daisyui from 'daisyui'
export default {
	content: ['../**/*.html', '../**/*.templ', '../**/*.go'],
	theme: {},
	plugins: [daisyui],
	daisyui: {
		themes: [
			{
				dim: {
					...require('daisyui/src/theming/themes')['dim'],
					info: '#9ED0F1',
					error: '#fe7c5d',
				},
			},
			'light',
			'dark',
			'cupcake',
			'bumblebee',
			'emerald',
			'corporate',
			'synthwave',
			'retro',
			'cyberpunk',
			'valentine',
			'halloween',
			'garden',
			'forest',
			'aqua',
			'lofi',
			'pastel',
			'fantasy',
			'wireframe',
			'black',
			'luxury',
			'dracula',
			'cmyk',
			'autumn',
			'business',
			'acid',
			'lemonade',
			'night',
			'coffee',
			'winter',
			'dim',
			'nord',
			'sunset',
		],
	},
}
