/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth.index'
import { Route as AuthTeamRouteImport } from './routes/_auth.team'
import { Route as AuthCalendarYearMonthRouteImport } from './routes/_auth.calendar.$year.$month'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTeamRoute = AuthTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCalendarYearMonthRoute = AuthCalendarYearMonthRouteImport.update({
  id: '/calendar/$year/$month',
  path: '/calendar/$year/$month',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/team': typeof AuthTeamRoute
  '/': typeof AuthIndexRoute
  '/calendar/$year/$month': typeof AuthCalendarYearMonthRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/team': typeof AuthTeamRoute
  '/': typeof AuthIndexRoute
  '/calendar/$year/$month': typeof AuthCalendarYearMonthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/team': typeof AuthTeamRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/calendar/$year/$month': typeof AuthCalendarYearMonthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login' | '/team' | '/' | '/calendar/$year/$month'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/team' | '/' | '/calendar/$year/$month'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/_auth/team'
    | '/_auth/'
    | '/_auth/calendar/$year/$month'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/team': {
      id: '/_auth/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthTeamRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/calendar/$year/$month': {
      id: '/_auth/calendar/$year/$month'
      path: '/calendar/$year/$month'
      fullPath: '/calendar/$year/$month'
      preLoaderRoute: typeof AuthCalendarYearMonthRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthTeamRoute: typeof AuthTeamRoute
  AuthIndexRoute: typeof AuthIndexRoute
  AuthCalendarYearMonthRoute: typeof AuthCalendarYearMonthRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthTeamRoute: AuthTeamRoute,
  AuthIndexRoute: AuthIndexRoute,
  AuthCalendarYearMonthRoute: AuthCalendarYearMonthRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
