/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth.index'
import { Route as AuthTeamRouteImport } from './routes/_auth.team'
import { Route as AuthAdminRouteImport } from './routes/_auth._admin'
import { Route as AuthAdminTokensRouteImport } from './routes/_auth._admin.tokens'
import { Route as AuthAdminSettingsRouteImport } from './routes/_auth._admin.settings'
import { Route as AuthAdminRequestsRouteImport } from './routes/_auth._admin.requests'
import { Route as AuthAdminExportRouteImport } from './routes/_auth._admin.export'
import { Route as AuthCalendarYearMonthRouteImport } from './routes/_auth.calendar.$year.$month'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTeamRoute = AuthTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminRoute = AuthAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminTokensRoute = AuthAdminTokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthAdminSettingsRoute = AuthAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthAdminRequestsRoute = AuthAdminRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthAdminExportRoute = AuthAdminExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthCalendarYearMonthRoute = AuthCalendarYearMonthRouteImport.update({
  id: '/calendar/$year/$month',
  path: '/calendar/$year/$month',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/team': typeof AuthTeamRoute
  '/': typeof AuthIndexRoute
  '/export': typeof AuthAdminExportRoute
  '/requests': typeof AuthAdminRequestsRoute
  '/settings': typeof AuthAdminSettingsRoute
  '/tokens': typeof AuthAdminTokensRoute
  '/calendar/$year/$month': typeof AuthCalendarYearMonthRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/team': typeof AuthTeamRoute
  '/': typeof AuthIndexRoute
  '/export': typeof AuthAdminExportRoute
  '/requests': typeof AuthAdminRequestsRoute
  '/settings': typeof AuthAdminSettingsRoute
  '/tokens': typeof AuthAdminTokensRoute
  '/calendar/$year/$month': typeof AuthCalendarYearMonthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/_admin': typeof AuthAdminRouteWithChildren
  '/_auth/team': typeof AuthTeamRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/_admin/export': typeof AuthAdminExportRoute
  '/_auth/_admin/requests': typeof AuthAdminRequestsRoute
  '/_auth/_admin/settings': typeof AuthAdminSettingsRoute
  '/_auth/_admin/tokens': typeof AuthAdminTokensRoute
  '/_auth/calendar/$year/$month': typeof AuthCalendarYearMonthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/team'
    | '/'
    | '/export'
    | '/requests'
    | '/settings'
    | '/tokens'
    | '/calendar/$year/$month'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/team'
    | '/'
    | '/export'
    | '/requests'
    | '/settings'
    | '/tokens'
    | '/calendar/$year/$month'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/_auth/_admin'
    | '/_auth/team'
    | '/_auth/'
    | '/_auth/_admin/export'
    | '/_auth/_admin/requests'
    | '/_auth/_admin/settings'
    | '/_auth/_admin/tokens'
    | '/_auth/calendar/$year/$month'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/team': {
      id: '/_auth/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthTeamRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/_admin': {
      id: '/_auth/_admin'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthAdminRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/_admin/tokens': {
      id: '/_auth/_admin/tokens'
      path: '/tokens'
      fullPath: '/tokens'
      preLoaderRoute: typeof AuthAdminTokensRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/_admin/settings': {
      id: '/_auth/_admin/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthAdminSettingsRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/_admin/requests': {
      id: '/_auth/_admin/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof AuthAdminRequestsRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/_admin/export': {
      id: '/_auth/_admin/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof AuthAdminExportRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/calendar/$year/$month': {
      id: '/_auth/calendar/$year/$month'
      path: '/calendar/$year/$month'
      fullPath: '/calendar/$year/$month'
      preLoaderRoute: typeof AuthCalendarYearMonthRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthAdminRouteChildren {
  AuthAdminExportRoute: typeof AuthAdminExportRoute
  AuthAdminRequestsRoute: typeof AuthAdminRequestsRoute
  AuthAdminSettingsRoute: typeof AuthAdminSettingsRoute
  AuthAdminTokensRoute: typeof AuthAdminTokensRoute
}

const AuthAdminRouteChildren: AuthAdminRouteChildren = {
  AuthAdminExportRoute: AuthAdminExportRoute,
  AuthAdminRequestsRoute: AuthAdminRequestsRoute,
  AuthAdminSettingsRoute: AuthAdminSettingsRoute,
  AuthAdminTokensRoute: AuthAdminTokensRoute,
}

const AuthAdminRouteWithChildren = AuthAdminRoute._addFileChildren(
  AuthAdminRouteChildren,
)

interface AuthRouteChildren {
  AuthAdminRoute: typeof AuthAdminRouteWithChildren
  AuthTeamRoute: typeof AuthTeamRoute
  AuthIndexRoute: typeof AuthIndexRoute
  AuthCalendarYearMonthRoute: typeof AuthCalendarYearMonthRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAdminRoute: AuthAdminRouteWithChildren,
  AuthTeamRoute: AuthTeamRoute,
  AuthIndexRoute: AuthIndexRoute,
  AuthCalendarYearMonthRoute: AuthCalendarYearMonthRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
