name: Deploy to Server

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test ./...

  build-and-push-image:
    needs:
      - build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: infrastructure/Chrono/Dockerfile
          push: true
          tags: |
            ghcr.io/the-apic/chrono:latest
            ghcr.io/the-apic/chrono:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build-and-push-image
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: create env file
      run: |
        echo "GIT_COMMIT_HASH=${{ github.sha }}" >> envfile
    - name: Docker Stack Deploy
      uses: cssnr/stack-deploy-action@v1
      with:
        name: chrono
        file: docker-compose.yaml
        host: theapic.com
        user: apic
        ssh_key: ${{ secrets.DEPLOY_SSH_KEY }}
        env_file: ./envfile
